import {
  Account,
  BudgetCategory,
  Category,
  FinancialGoal,
  PlannedPurchase,
  Subscription,
  Transaction,
  UserProfile,
} from '../types/finance';

export const INITIAL_USER: UserProfile = {
  id: 'usr_prod_01',
  name: 'Rahul Sharma',
  username: 'rahul_fin',
  email: 'rahul.sharma@example.com',
  occupation: 'Senior Full Stack Engineer',
  company: 'Tech Innovations Labs',
  phone: '+91 98765 43210',
  bio: 'Software engineer focused on disciplined saving, deliberate tech purchases, and building long-term financial resilience.',
  currency: 'INR',
  country: 'India',
  monthlySalary: 60000,
  salaryDate: 1,
  incomeType: 'monthly',
  minimumEmergencyReserve: 50000,
  discretionaryBudgetPercent: 25,
  theme: 'dark',
  isOnboarded: true,
  isDemo: true,
  lastLoginAt: '2026-08-14T11:00:00.000Z',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  notificationPreferences: {
    upcomingBills: true,
    budgetAlerts: true,
    goalMilestones: true,
    subscriptionRenewals: true,
    monthlyReview: true,
  },
};

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat_housing', name: 'Housing & Rent', key: 'housing', icon: 'Home', color: '#6366f1' },
  { id: 'cat_food', name: 'Food & Dining', key: 'food', icon: 'Utensils', color: '#f97316' },
  { id: 'cat_transport', name: 'Transport & Fuel', key: 'transport', icon: 'Car', color: '#06b6d4' },
  { id: 'cat_utilities', name: 'Utilities & Internet', key: 'utilities', icon: 'Zap', color: '#eab308' },
  { id: 'cat_shopping', name: 'Shopping & Gear', key: 'shopping', icon: 'ShoppingBag', color: '#ec4899' },
  { id: 'cat_entertainment', name: 'Entertainment & Leisure', key: 'entertainment', icon: 'Film', color: '#a855f7' },
  { id: 'cat_healthcare', name: 'Healthcare & Fitness', key: 'healthcare', icon: 'HeartPulse', color: '#10b981' },
  { id: 'cat_subscriptions', name: 'Subscriptions & SaaS', key: 'subscriptions', icon: 'Repeat', color: '#3b82f6' },
  { id: 'cat_debt', name: 'Debt & EMI Payments', key: 'debt', icon: 'CreditCard', color: '#ef4444' },
  { id: 'cat_savings', name: 'Savings & Investments', key: 'savings', icon: 'PiggyBank', color: '#14b8a6' },
  { id: 'cat_salary', name: 'Salary & Primary Income', key: 'salary', icon: 'Briefcase', color: '#22c55e' },
  { id: 'cat_freelance', name: 'Freelance & Side Gigs', key: 'freelance', icon: 'Coins', color: '#8b5cf6' },
  { id: 'cat_travel', name: 'Travel & Vacations', key: 'travel', icon: 'Plane', color: '#f43f5e' },
  { id: 'cat_other', name: 'Other Discretionary', key: 'other', icon: 'MoreHorizontal', color: '#64748b' },
];

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc_primary_bank',
    name: 'HDFC Salary Account',
    type: 'bank',
    balance: 48500,
    institution: 'HDFC Bank',
    accountNumberMask: '•••• 4821',
    color: '#0284c7',
  },
  {
    id: 'acc_emergency_savings',
    name: 'High-Yield Emergency Fund',
    type: 'savings',
    balance: 95000,
    institution: 'ICICI Direct 7.1%',
    accountNumberMask: '•••• 9102',
    color: '#10b981',
  },
  {
    id: 'acc_wallet_cash',
    name: 'Cash & UPI Reserve',
    type: 'cash',
    balance: 4200,
    institution: 'Liquid Cash',
    accountNumberMask: 'UPI Wallet',
    color: '#f59e0b',
  },
  {
    id: 'acc_credit_card',
    name: 'Regalia Gold Credit Card',
    type: 'credit',
    balance: 12400, // outstanding balance
    institution: 'HDFC Cards',
    accountNumberMask: '•••• 7734',
    color: '#ef4444',
  },
];

export const INITIAL_BUDGETS: BudgetCategory[] = [
  { id: 'b_housing', categoryId: 'cat_housing', categoryName: 'Housing & Rent', categoryKey: 'housing', monthlyLimit: 18000, color: '#6366f1' },
  { id: 'b_food', categoryId: 'cat_food', categoryName: 'Food & Dining', categoryKey: 'food', monthlyLimit: 8500, color: '#f97316' },
  { id: 'b_utilities', categoryId: 'cat_utilities', categoryName: 'Utilities & Internet', categoryKey: 'utilities', monthlyLimit: 3200, color: '#eab308' },
  { id: 'b_transport', categoryId: 'cat_transport', categoryName: 'Transport & Fuel', categoryKey: 'transport', monthlyLimit: 4000, color: '#06b6d4' },
  { id: 'b_shopping', categoryId: 'cat_shopping', categoryName: 'Shopping & Gear', categoryKey: 'shopping', monthlyLimit: 5000, color: '#ec4899' },
  { id: 'b_entertainment', categoryId: 'cat_entertainment', categoryName: 'Entertainment & Leisure', categoryKey: 'entertainment', monthlyLimit: 3000, color: '#a855f7' },
  { id: 'b_subscriptions', categoryId: 'cat_subscriptions', categoryName: 'Subscriptions & SaaS', categoryKey: 'subscriptions', monthlyLimit: 3500, color: '#3b82f6' },
  { id: 'b_healthcare', categoryId: 'cat_healthcare', categoryName: 'Healthcare & Fitness', categoryKey: 'healthcare', monthlyLimit: 2500, color: '#10b981' },
];

export const INITIAL_GOALS: FinancialGoal[] = [
  {
    id: 'goal_laptop',
    name: 'MacBook Pro M3 / Dev Machine',
    category: 'laptop',
    targetAmount: 80000,
    currentAmount: 48000,
    monthlyContribution: 8000,
    targetDate: '2026-12-15',
    startDate: '2026-04-01',
    priority: 'high',
    isPaused: false,
    isCompleted: false,
    notes: 'Upgrading work station for better local Docker compile speed and battery life.',
    color: '#6366f1',
  },
  {
    id: 'goal_emergency',
    name: '6-Month Emergency Safety Net',
    category: 'emergency',
    targetAmount: 150000,
    currentAmount: 95000,
    monthlyContribution: 5000,
    targetDate: '2027-04-30',
    startDate: '2025-11-01',
    priority: 'high',
    isPaused: false,
    isCompleted: false,
    notes: 'Calculated as 6 months of baseline essential survival expenses.',
    color: '#10b981',
  },
  {
    id: 'goal_travel',
    name: 'Ladakh High-Pass Roadtrip',
    category: 'travel',
    targetAmount: 35000,
    currentAmount: 16500,
    monthlyContribution: 3500,
    targetDate: '2027-01-20',
    startDate: '2026-06-01',
    priority: 'medium',
    isPaused: false,
    isCompleted: false,
    notes: 'Bike rental, gear, permits, and homestays.',
    color: '#f43f5e',
  },
];

export const INITIAL_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub_netflix',
    name: 'Netflix 4K HDR',
    amount: 649,
    billingCycle: 'monthly',
    nextBillingDate: '2026-08-22',
    category: 'Entertainment',
    paymentMethod: 'Credit Card',
    url: 'https://netflix.com',
    status: 'active',
    color: '#e50914',
  },
  {
    id: 'sub_spotify',
    name: 'Spotify Premium Duo',
    amount: 179,
    billingCycle: 'monthly',
    nextBillingDate: '2026-08-25',
    category: 'Entertainment',
    paymentMethod: 'UPI AutoPay',
    url: 'https://spotify.com',
    status: 'active',
    color: '#1db954',
  },
  {
    id: 'sub_gym',
    name: 'Cult.fit Elite Gym Membership',
    amount: 1500,
    billingCycle: 'monthly',
    nextBillingDate: '2026-09-02',
    category: 'Fitness',
    paymentMethod: 'Bank AutoDebit',
    status: 'active',
    color: '#ff3278',
  },
  {
    id: 'sub_broadband',
    name: 'Airtel Xstream Fiber 200Mbps',
    amount: 999,
    billingCycle: 'monthly',
    nextBillingDate: '2026-08-28',
    category: 'Utilities',
    paymentMethod: 'Credit Card',
    status: 'active',
    color: '#ea1d24',
  },
  {
    id: 'sub_icloud',
    name: 'Apple iCloud+ & Dev Storage 2TB',
    amount: 219,
    billingCycle: 'monthly',
    nextBillingDate: '2026-08-19',
    category: 'Cloud Storage',
    paymentMethod: 'Debit Card',
    status: 'active',
    color: '#0071e3',
  },
  {
    id: 'sub_insurance',
    name: 'HDFC Ergo Health Term Cover',
    amount: 1420,
    billingCycle: 'monthly',
    nextBillingDate: '2026-09-05',
    category: 'Insurance',
    paymentMethod: 'Bank Direct Debit',
    status: 'active',
    color: '#0284c7',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_salary_aug',
    amount: 60000,
    type: 'income',
    date: '2026-08-01',
    categoryId: 'cat_salary',
    categoryName: 'Salary & Primary Income',
    categoryKey: 'salary',
    description: 'TechCorp Monthly Salary (Direct Deposit)',
    account: 'HDFC Salary Account',
    paymentMethod: 'Bank Transfer',
    notes: 'August salary credited successfully.',
  },
  {
    id: 'tx_rent_aug',
    amount: 18000,
    type: 'expense',
    date: '2026-08-02',
    categoryId: 'cat_housing',
    categoryName: 'Housing & Rent',
    categoryKey: 'housing',
    description: 'Apartment Rent (Indiranagar, Bangalore)',
    account: 'HDFC Salary Account',
    paymentMethod: 'UPI',
    isRecurring: true,
  },
  {
    id: 'tx_goal_laptop_aug',
    amount: 8000,
    type: 'expense',
    date: '2026-08-03',
    categoryId: 'cat_savings',
    categoryName: 'Savings & Investments',
    categoryKey: 'savings',
    description: 'MacBook Pro Goal Automated SIP',
    account: 'HDFC Salary Account',
    paymentMethod: 'Bank Transfer',
    goalId: 'goal_laptop',
  },
  {
    id: 'tx_goal_emergency_aug',
    amount: 5000,
    type: 'expense',
    date: '2026-08-03',
    categoryId: 'cat_savings',
    categoryName: 'Savings & Investments',
    categoryKey: 'savings',
    description: 'Emergency Reserve Monthly Deposit',
    account: 'High-Yield Emergency Fund',
    paymentMethod: 'Bank Transfer',
    goalId: 'goal_emergency',
  },
  {
    id: 'tx_groceries_01',
    amount: 2450,
    type: 'expense',
    date: '2026-08-04',
    categoryId: 'cat_food',
    categoryName: 'Food & Dining',
    categoryKey: 'food',
    description: 'Nature Basket Organic Groceries & Staples',
    account: 'HDFC Salary Account',
    paymentMethod: 'UPI',
  },
  {
    id: 'tx_electricity_aug',
    amount: 1480,
    type: 'expense',
    date: '2026-08-05',
    categoryId: 'cat_utilities',
    categoryName: 'Utilities & Internet',
    categoryKey: 'utilities',
    description: 'BESCOM Electricity Bill',
    account: 'HDFC Salary Account',
    paymentMethod: 'UPI',
  },
  {
    id: 'tx_dining_weekend',
    amount: 1850,
    type: 'expense',
    date: '2026-08-08',
    categoryId: 'cat_food',
    categoryName: 'Food & Dining',
    categoryKey: 'food',
    description: 'Dinner with Team @ Toit Brewpub',
    account: 'Regalia Gold Credit Card',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'tx_uber_rides',
    amount: 720,
    type: 'expense',
    date: '2026-08-09',
    categoryId: 'cat_transport',
    categoryName: 'Transport & Fuel',
    categoryKey: 'transport',
    description: 'Uber Commute Airport Express',
    account: 'HDFC Salary Account',
    paymentMethod: 'UPI',
  },
  {
    id: 'tx_freelance_ui',
    amount: 15000,
    type: 'income',
    date: '2026-08-10',
    categoryId: 'cat_freelance',
    categoryName: 'Freelance & Side Gigs',
    categoryKey: 'freelance',
    description: 'Design Consulting: Fintech Mobile App Audit',
    account: 'HDFC Salary Account',
    paymentMethod: 'Bank Transfer',
    notes: 'Milestone 1 payment received.',
  },
  {
    id: 'tx_gym_sub',
    amount: 1500,
    type: 'expense',
    date: '2026-08-11',
    categoryId: 'cat_subscriptions',
    categoryName: 'Subscriptions & SaaS',
    categoryKey: 'subscriptions',
    description: 'Cult.fit Monthly Membership',
    account: 'HDFC Salary Account',
    paymentMethod: 'Bank Transfer',
    isRecurring: true,
  },
  {
    id: 'tx_book_store',
    amount: 890,
    type: 'expense',
    date: '2026-08-12',
    categoryId: 'cat_shopping',
    categoryName: 'Shopping & Gear',
    categoryKey: 'shopping',
    description: 'Book: Designing Data-Intensive Applications',
    account: 'Regalia Gold Credit Card',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'tx_coffee_shop',
    amount: 340,
    type: 'expense',
    date: '2026-08-13',
    categoryId: 'cat_food',
    categoryName: 'Food & Dining',
    categoryKey: 'food',
    description: 'Blue Tokai Roasters Pour-over Coffee',
    account: 'Cash & UPI Reserve',
    paymentMethod: 'UPI',
  },
];

export const INITIAL_PLANNED_PURCHASES: PlannedPurchase[] = [
  {
    id: 'plan_macbook',
    title: 'MacBook Pro M3 Max 36GB',
    price: 185000,
    targetDate: '2026-11-30',
    category: 'Workstation Tech',
    paymentMethod: 'savings',
    notes: 'Primary development workstation upgrade for local LLMs and compilation workloads.',
    createdAt: '2026-08-01',
  },
  {
    id: 'plan_sony_headphones',
    title: 'Sony WH-1000XM5 ANC Headphones',
    price: 26990,
    targetDate: '2026-09-15',
    category: 'Audio Gear',
    paymentMethod: 'cash',
    notes: 'Active noise cancellation for deep work and travel.',
    createdAt: '2026-08-05',
  },
  {
    id: 'plan_standing_desk',
    title: 'Ergonomic Motorized Standing Desk',
    price: 32000,
    targetDate: '2026-10-10',
    category: 'Ergonomics',
    paymentMethod: 'savings',
    notes: 'Dual motor height adjustable sit-stand desk.',
    createdAt: '2026-08-08',
  },
];

export const PRESET_USERS: Array<{
  profile: UserProfile;
  accounts: Account[];
  budgets: BudgetCategory[];
  goals: FinancialGoal[];
  subscriptions: Subscription[];
  transactions: Transaction[];
  description: string;
  tag: string;
}> = [
  {
    profile: INITIAL_USER,
    accounts: INITIAL_ACCOUNTS,
    budgets: INITIAL_BUDGETS,
    goals: INITIAL_GOALS,
    subscriptions: INITIAL_SUBSCRIPTIONS,
    transactions: INITIAL_TRANSACTIONS,
    description: 'Senior Software Engineer with disciplined emergency reserves & active gadget SIPs',
    tag: 'Tech Lead • ₹60k/mo',
  },
  {
    profile: {
      id: 'usr_priya_02',
      name: 'Priya Patel',
      username: 'priya_design',
      email: 'priya.design@example.com',
      occupation: 'Principal Product Designer',
      company: 'Fintech Studio Inc',
      phone: '+91 99887 11223',
      bio: 'Design leader optimizing high savings velocity and international conference travel fund.',
      currency: 'INR',
      country: 'India',
      monthlySalary: 125000,
      salaryDate: 28,
      incomeType: 'monthly',
      minimumEmergencyReserve: 150000,
      discretionaryBudgetPercent: 30,
      theme: 'dark',
      isOnboarded: true,
      isDemo: true,
      lastLoginAt: '2026-08-14T10:30:00.000Z',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      notificationPreferences: {
        upcomingBills: true,
        budgetAlerts: true,
        goalMilestones: true,
        subscriptionRenewals: true,
        monthlyReview: true,
      },
    },
    accounts: [
      {
        id: 'acc_priya_hdfc',
        name: 'HDFC Imperia Salary',
        type: 'bank',
        balance: 112000,
        institution: 'HDFC Bank',
        accountNumberMask: '•••• 6631',
        color: '#0284c7',
      },
      {
        id: 'acc_priya_reserve',
        name: 'Quantum Liquid Emergency Fund',
        type: 'savings',
        balance: 240000,
        institution: 'Quantum AMC',
        accountNumberMask: '•••• 1009',
        color: '#10b981',
      },
      {
        id: 'acc_priya_infinia',
        name: 'Infinia Metal Card',
        type: 'credit',
        balance: 18500,
        institution: 'HDFC Cards',
        accountNumberMask: '•••• 8821',
        color: '#ef4444',
      },
    ],
    budgets: [
      { id: 'b_p_housing', categoryId: 'cat_housing', categoryName: 'Housing & Rent', categoryKey: 'housing', monthlyLimit: 32000, color: '#6366f1' },
      { id: 'b_p_food', categoryId: 'cat_food', categoryName: 'Food & Dining', categoryKey: 'food', monthlyLimit: 14000, color: '#f97316' },
      { id: 'b_p_travel', categoryId: 'cat_travel', categoryName: 'Travel & Vacations', categoryKey: 'travel', monthlyLimit: 15000, color: '#f43f5e' },
      { id: 'b_p_shopping', categoryId: 'cat_shopping', categoryName: 'Shopping & Gear', categoryKey: 'shopping', monthlyLimit: 12000, color: '#ec4899' },
    ],
    goals: [
      {
        id: 'goal_priya_japan',
        name: 'Tokyo Design Conference 2027',
        category: 'travel',
        targetAmount: 250000,
        currentAmount: 140000,
        monthlyContribution: 15000,
        targetDate: '2027-04-15',
        startDate: '2026-01-01',
        priority: 'high',
        isPaused: false,
        isCompleted: false,
        color: '#f43f5e',
      },
      {
        id: 'goal_priya_retirement',
        name: 'Nifty Index Wealth Accumulator',
        category: 'investment',
        targetAmount: 1000000,
        currentAmount: 480000,
        monthlyContribution: 25000,
        targetDate: '2029-12-31',
        startDate: '2025-06-01',
        priority: 'high',
        isPaused: false,
        isCompleted: false,
        color: '#10b981',
      },
    ],
    subscriptions: [
      { id: 'sub_figma', name: 'Figma Professional & AI', amount: 1250, billingCycle: 'monthly', nextBillingDate: '2026-08-25', category: 'Software & Tools', paymentMethod: 'Credit Card', status: 'active', color: '#a855f7' },
      { id: 'sub_chatgpt', name: 'ChatGPT Plus Team', amount: 1999, billingCycle: 'monthly', nextBillingDate: '2026-08-20', category: 'AI Tools', paymentMethod: 'Credit Card', status: 'active', color: '#10b981' },
    ],
    transactions: INITIAL_TRANSACTIONS,
    description: 'High-income design lead targeting aggressive index fund growth and sabbatical travel',
    tag: 'Design Lead • ₹125k/mo',
  },
  {
    profile: {
      id: 'usr_amit_03',
      name: 'Amit Verma',
      username: 'amit_devops',
      email: 'amit.verma@example.com',
      occupation: 'Junior DevOps Engineer',
      company: 'CloudScale Technologies',
      phone: '+91 91234 56780',
      bio: 'First job earner establishing disciplined budgeting and building initial 6-month safety buffer.',
      currency: 'INR',
      country: 'India',
      monthlySalary: 42000,
      salaryDate: 5,
      incomeType: 'monthly',
      minimumEmergencyReserve: 30000,
      discretionaryBudgetPercent: 20,
      theme: 'dark',
      isOnboarded: true,
      isDemo: true,
      lastLoginAt: '2026-08-14T09:15:00.000Z',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      notificationPreferences: {
        upcomingBills: true,
        budgetAlerts: true,
        goalMilestones: true,
        subscriptionRenewals: true,
        monthlyReview: true,
      },
    },
    accounts: [
      {
        id: 'acc_amit_sbi',
        name: 'SBI Salary Node',
        type: 'bank',
        balance: 29400,
        institution: 'State Bank of India',
        accountNumberMask: '•••• 3199',
        color: '#0284c7',
      },
      {
        id: 'acc_amit_fd',
        name: 'Emergency Fixed Deposit',
        type: 'savings',
        balance: 35000,
        institution: 'SBI e-FD',
        accountNumberMask: '•••• 9942',
        color: '#10b981',
      },
    ],
    budgets: [
      { id: 'b_a_rent', categoryId: 'cat_housing', categoryName: 'Shared PG & Rent', categoryKey: 'housing', monthlyLimit: 14000, color: '#6366f1' },
      { id: 'b_a_food', categoryId: 'cat_food', categoryName: 'Mess & Food', categoryKey: 'food', monthlyLimit: 7000, color: '#f97316' },
      { id: 'b_a_commute', categoryId: 'cat_transport', categoryName: 'Metro & Commute', categoryKey: 'transport', monthlyLimit: 3000, color: '#06b6d4' },
    ],
    goals: [
      {
        id: 'goal_amit_laptop',
        name: 'Linux Workstation Upgrade',
        category: 'electronics',
        targetAmount: 65000,
        currentAmount: 22000,
        monthlyContribution: 5500,
        targetDate: '2027-02-28',
        startDate: '2026-03-01',
        priority: 'medium',
        isPaused: false,
        isCompleted: false,
        color: '#3b82f6',
      },
    ],
    subscriptions: [
      { id: 'sub_spotify_amit', name: 'Spotify Student', amount: 59, billingCycle: 'monthly', nextBillingDate: '2026-08-29', category: 'Entertainment', paymentMethod: 'UPI AutoPay', status: 'active', color: '#1db954' },
    ],
    transactions: INITIAL_TRANSACTIONS,
    description: 'First-job tech earner budgeting rent, mess, certifications & starter emergency fund',
    tag: 'Junior DevOps • ₹42k/mo',
  },
  {
    profile: {
      id: 'usr_elena_04',
      name: 'Elena Vance',
      username: 'elena_vance',
      email: 'elena.vance@example.com',
      occupation: 'Global Strategy Consultant',
      company: 'McKinsey & Co / Independent',
      phone: '+1 (415) 555-0192',
      bio: 'Management consultant working with multinational clients across US, EU and APAC.',
      currency: 'USD',
      country: 'United States',
      monthlySalary: 7500,
      salaryDate: 15,
      incomeType: 'monthly',
      minimumEmergencyReserve: 15000,
      discretionaryBudgetPercent: 25,
      theme: 'dark',
      isOnboarded: true,
      isDemo: true,
      lastLoginAt: '2026-08-14T08:45:00.000Z',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      notificationPreferences: {
        upcomingBills: true,
        budgetAlerts: true,
        goalMilestones: true,
        subscriptionRenewals: true,
        monthlyReview: true,
      },
    },
    accounts: [
      {
        id: 'acc_elena_chase',
        name: 'Chase Premier Checking',
        type: 'bank',
        balance: 6200,
        institution: 'Chase Bank',
        accountNumberMask: '•••• 1209',
        color: '#0284c7',
      },
      {
        id: 'acc_elena_marcus',
        name: 'Marcus High Yield Cash (4.4%)',
        type: 'savings',
        balance: 22500,
        institution: 'Goldman Sachs Marcus',
        accountNumberMask: '•••• 8820',
        color: '#10b981',
      },
      {
        id: 'acc_elena_sapphire',
        name: 'Chase Sapphire Reserve',
        type: 'credit',
        balance: 1420,
        institution: 'Chase Credit',
        accountNumberMask: '•••• 9901',
        color: '#ef4444',
      },
    ],
    budgets: [
      { id: 'b_e_housing', categoryId: 'cat_housing', categoryName: 'Apartment & Utilities', categoryKey: 'housing', monthlyLimit: 2600, color: '#6366f1' },
      { id: 'b_e_food', categoryId: 'cat_food', categoryName: 'Dining & Groceries', categoryKey: 'food', monthlyLimit: 950, color: '#f97316' },
      { id: 'b_e_travel', categoryId: 'cat_travel', categoryName: 'Client Travel Out-of-Pocket', categoryKey: 'travel', monthlyLimit: 800, color: '#f43f5e' },
    ],
    goals: [
      {
        id: 'goal_elena_roth',
        name: 'Vanguard Total Stock Index',
        category: 'investment',
        targetAmount: 50000,
        currentAmount: 28000,
        monthlyContribution: 1200,
        targetDate: '2028-06-30',
        startDate: '2025-01-01',
        priority: 'high',
        isPaused: false,
        isCompleted: false,
        color: '#10b981',
      },
    ],
    subscriptions: [
      { id: 'sub_wsj', name: 'Wall Street Journal Digital', amount: 35, billingCycle: 'monthly', nextBillingDate: '2026-08-28', category: 'News & Media', paymentMethod: 'Credit Card', status: 'active', color: '#0284c7' },
      { id: 'sub_claude', name: 'Claude Pro + Workspaces', amount: 40, billingCycle: 'monthly', nextBillingDate: '2026-08-19', category: 'AI Tools', paymentMethod: 'Credit Card', status: 'active', color: '#d97706' },
    ],
    transactions: INITIAL_TRANSACTIONS,
    description: 'International consultant managing USD cashflows, Marcus HYSA yields & Vanguard Indexing',
    tag: 'Strategy Consultant • $7.5k/mo',
  },
];

